# Makefile to cross-compile ucon-handler

PRJ_NAME=ucon-handler
DIST_SUBDIR=l

# what flavors to build
FLAVORS=_rel _dbg

SRCS=main.c pkt.c ucon.c romtag.c boot.c
HDRS=pkt.h ucon.h boot.h

include ../build.mk
